using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Media;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Automation;
using System.Windows.Media;
using AlatStatistik.Analysis;
using AlatStatistik.DataPrep;
using AlatStatistik.Models;
using AlatStatistik.Statistics;
using AlatStatistik.Validation;
using AlatStatistik.Views;
using Microsoft.Win32;

namespace AlatStatistik
{

    public partial class MainWindow : Window
    {
        
        
        
        public static readonly RoutedCommand CariAlat = new("CariAlat", typeof(MainWindow));
        public static readonly RoutedCommand UlangiAnalisis = new("UlangiAnalisis", typeof(MainWindow));
        public static readonly RoutedCommand EksporWord = new("EksporWord", typeof(MainWindow));
        public static readonly RoutedCommand EksporHasil = new("EksporHasil", typeof(MainWindow));
        public static readonly RoutedCommand SalinHasil = new("SalinHasil", typeof(MainWindow));
        public static readonly RoutedCommand PergiTab = new("PergiTab", typeof(MainWindow));

        
        
        
        private readonly List<ItemAlat> _semuaItem = new();

        private Dataset _data = new();
        private readonly List<AnalysisSpec> _analisis = AnalysisRunner.Semua();

        
        
        
        private AnalysisSpec? _ulangiSpec;
        private RunContext? _ulangiKonteks;

        
        
        private readonly Dictionary<string, JendelaDeskriptif> _jendelaDeskriptif = new();

        
        private readonly PenukarLabelNilai _penukarLabelNilai = new();
        private readonly RingkasanLabelNilai _ringkasanLabelNilai = new();
        private readonly PenukarNomorBaris _penukarNomorBaris = new();
        private DataGridTextColumn? _kolomNomorBaris;

        
        
        private Dataset? _cadanganData;

        
        
        private string? _nilaiSebelumEdit;

        
        
        private string? _simpanTerakhir;
        
        
        
        
        
        private readonly List<EntriKeluaran> _keluaran = new();

        public MainWindow()
        {
            InitializeComponent();
            BangunMenuAnalisis();
            _semuaItem.AddRange(Katalog.Semua(_analisis));

            GridData.AutoGeneratingColumn += GridData_AutoGeneratingColumn;
            GridData.AutoGeneratedColumns += GridData_AutoGeneratedColumns;
            MuatContohDiamDiam();

            
            var undo = new CommandBinding(ApplicationCommands.Undo);
            undo.Executed += (_, _) => UrubahanTerakhir();
            CommandBindings.Add(undo);

            
            var simpan = new CommandBinding(ApplicationCommands.Save);
            simpan.Executed += (_, _) => Simpan_Click(this, new RoutedEventArgs());
            CommandBindings.Add(simpan);

            
            
            CommandBindings.Add(new CommandBinding(CariAlat, (_, _) => CariAlat_Click(this, new RoutedEventArgs())));
            CommandBindings.Add(new CommandBinding(UlangiAnalisis, (_, _) => Ulangi_Click(this, new RoutedEventArgs())));
            CommandBindings.Add(new CommandBinding(EksporWord, (_, _) => EksporDocx_Click(this, new RoutedEventArgs())));
            CommandBindings.Add(new CommandBinding(EksporHasil, (_, _) => EksporHtml_Click(this, new RoutedEventArgs())));
            CommandBindings.Add(new CommandBinding(SalinHasil, (_, _) => SalinHasil_Click(this, new RoutedEventArgs())));
            CommandBindings.Add(new CommandBinding(PergiTab, (_, e) =>
            {
                if (e.Parameter is string teks && int.TryParse(teks, out int i)
                    && i >= 0 && i < TabUtama.Items.Count)
                    TabUtama.SelectedIndex = i;
            }));

            SegarkanRiwayat();
            SesuaikanUkuranAwal();
            SegarkanKeluaran();
            this.PusatkanDiLayarAktif();
        }

        
        
        
        
        private void SesuaikanUkuranAwal()
        {
            try
            {
                double lebar = SystemParameters.WorkArea.Width;
                double tinggi = SystemParameters.WorkArea.Height;

                
                
                if (Width > lebar) Width = Math.Max(MinWidth, lebar - 24);
                if (Height > tinggi) Height = Math.Max(MinHeight, tinggi - 24);
            }
            catch
            {
                
            }
        }

        

        private void MuatContohDiamDiam()
        {
            string? contoh = CariBerkas("samples", "data_uji.csv");
            if (contoh != null)
            {
                try
                {
                    var ds = DataImport.LoadCsv(contoh);
                    
                    
                    ds.SourcePath = null;
                    ds.Name = "data_uji (contoh)";
                    Tampilkan(ds);
                }
                catch {  }
            }
        }

        private void Tampilkan(Dataset ds)
        {
            _data = ds;
            SegarkanTampilanData();
            SegarkanRiwayat();
        }

        private void SegarkanTampilanData()
        {
            try
            {
                GridData.ItemsSource = _data.ToDataTable().DefaultView;
                BangunGridVariabel();
                InfoData.Text = $"{Path.GetFileName(_data.SourcePath ?? _data.Name)} — "
                              + $"{_data.RowCount} baris × {_data.ColumnCount} variabel";
            }
            catch (Exception ex)
            {
                TampilkanGalat(ex, "Gagal menyegarkan tabel Data");
            }
        }

        private void BangunGridVariabel()
        {
            GridVariabel.Columns.Clear();

            GridVariabel.Columns.Add(new DataGridTextColumn
            {
                Header = KeteranganKolomVariabel.Nama,
                Binding = new System.Windows.Data.Binding("Name"), Width = 160
            });
            GridVariabel.Columns.Add(new DataGridTextColumn
            {
                Header = KeteranganKolomVariabel.Label,
                Binding = new System.Windows.Data.Binding("Label"), Width = 180
            });

            var kolomUkur = new DataGridComboBoxColumn
            {
                Header = KeteranganKolomVariabel.TingkatUkur,
                SelectedItemBinding = new System.Windows.Data.Binding("Measure"),
                Width = 150
            };
            kolomUkur.ItemsSource = Enum.GetValues(typeof(Measure)).Cast<Measure>().ToList();
            GridVariabel.Columns.Add(kolomUkur);

            GridVariabel.Columns.Add(new DataGridTextColumn
            {
                Header = KeteranganKolomVariabel.Desimal,
                Binding = new System.Windows.Data.Binding("Decimals"), Width = 90
            });

            
            
            GridVariabel.Columns.Add(new DataGridTextColumn
            {
                Header = KeteranganKolomVariabel.LabelNilai,
                Binding = new System.Windows.Data.Binding(".")
                {
                    Converter = _ringkasanLabelNilai
                },
                Width = 200,
                IsReadOnly = true
            });

            

            if (!ReferenceEquals(GridVariabel.ItemsSource, _data.Variables))
                GridVariabel.ItemsSource = _data.Variables;

            PerbaruiInfoKolom();
        }

        
        
        private void GridData_AutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.Column is not DataGridTextColumn kolom) return;
            int idx = _data.IndexOf(e.PropertyName ?? "");
            var variabel = idx >= 0 && idx < _data.Variables.Count ? _data.Variables[idx] : null;
            kolom.Binding = new System.Windows.Data.Binding(e.PropertyName ?? "")
            {
                Converter = _penukarLabelNilai,
                ConverterParameter = variabel
            };
        }

        private void GridData_AutoGeneratedColumns(object? sender, EventArgs e)
            => TambahkanKolomNomorBaris();

        private void TambahkanKolomNomorBaris()
        {
            if (_kolomNomorBaris != null && GridData.Columns.Contains(_kolomNomorBaris)) return;

            var kolom = new DataGridTextColumn
            {
                Header = "",
                IsReadOnly = true,
                CanUserSort = false,
                CanUserReorder = false,
                CanUserResize = false,
                MinWidth = 40,
                Width = new DataGridLength(46, DataGridLengthUnitType.Pixel),
                Binding = new System.Windows.Data.Binding
                {
                    Converter = _penukarNomorBaris
                }
            };

            var gayaSel = new Style(typeof(TextBlock));
            gayaSel.Setters.Add(new Setter(TextBlock.TextAlignmentProperty, TextAlignment.Center));
            kolom.ElementStyle = gayaSel;

            var gayaJudul = new Style(typeof(DataGridColumnHeader));
            gayaJudul.Setters.Add(new Setter(Control.HorizontalContentAlignmentProperty, HorizontalAlignment.Center));
            kolom.HeaderStyle = gayaJudul;

            GridData.Columns.Insert(0, kolom);
            _kolomNomorBaris = kolom;
        }

        
        
        
        private void LabelNilai_Click(object sender, RoutedEventArgs e)
        {
            PenukarLabelNilai.Aktif = ItemLabelNilai.IsChecked == true;
            GridData.ItemsSource = _data.ToDataTable().DefaultView;
        }

        

        private void GridVariabel_CurrentCellChanged(object sender, EventArgs e)
            => PerbaruiInfoKolom();

        private void GridVariabel_SelectionChanged(object sender, SelectionChangedEventArgs e)
            => PerbaruiInfoKolom();

        private void PerbaruiInfoKolom()
        {
            if (InfoKolomVariabel == null) return;
            string kolom = GridVariabel.CurrentColumn?.Header?.ToString() ?? "";
            InfoKolomVariabel.Text = KeteranganKolomVariabel.Untuk(kolom);
        }

        // DataGrid membuat baris baru lewat konstruktor kosong, jadi
        // variabelnya tanpa nama. Beri nama baku yang unik sejak awal.
        private void GridVariabel_AddingNewItem(object sender, AddingNewItemEventArgs e)
        {
            try
            {
                string usul = "V" + (_data.ColumnCount + 1);
                e.NewItem = new Variable { Name = _data.NamaVariabelUnik(usul) };
            }
            catch (Exception ex)
            {
                App.TulisJejak("AddingNewItem variabel gagal: " + ex.Message);
            }
        }

        // Jaring pengaman sebelum tab Data ditampilkan.
        private void TabUtama_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (TabUtama.SelectedIndex != 0) return;

            try
            {
                if (_data.SinkronkanStruktur())
                    GridData.ItemsSource = _data.ToDataTable().DefaultView;
            }
            catch (Exception ex)
            {
                TampilkanGalat(ex, "Gagal menyiapkan tabel Data");
            }
        }

        

        private void BangunMenuAnalisis()
        {
            
            
            
            
            
            
            foreach (string kategori in AnalysisRunner.Kategori(_analisis))
            {
                var dalamKategori = _analisis.Where(s => s.Category == kategori && !s.IsML).ToList();
                if (dalamKategori.Count == 0) continue;

                var menu = new MenuItem { Header = kategori };

                foreach (var spec in dalamKategori)
                    menu.Items.Add(BuatItemAlat(spec));

                MenuAnalisis.Items.Add(menu);
            }

            var ml = _analisis.Where(s => s.IsML).ToList();
            if (ml.Count > 0)
            {
                var menuMl = new MenuItem { Header = "ML" };
                foreach (var spec in ml)
                    menuMl.Items.Add(BuatItemAlat(spec));
                MenuAnalisis.Items.Add(menuMl);
            }
        }

        
        
        
        private MenuItem BuatItemAlat(AnalysisSpec spec)
        {
            var item = new MenuItem { Header = spec.Name, Tag = spec };
            item.Click += (_, _) => BukaAnalisis(spec);
            return item;
        }

        
        
        
        
        
        
        private void CariAlat_Click(object sender, RoutedEventArgs e)
        {
            var spec = PeluncurAlat.Tanya(_semuaItem, this);
            if (spec != null) BukaAnalisis(spec);
        }

        
        
        
        
        
        private void BukaAnalisis(AnalysisSpec spec)
        {
            
            
            
            if (spec.Category == "Deskriptif")
            {
                InfoAnalisis.Text = $"{spec.Category} — {spec.Name} — jendela tersendiri";
                BukaJendelaDeskriptif(spec);
                return;
            }

            if (_data.IsEmpty)
            {
                MessageBox.Show(
                    "Belum ada data. Buka berkas data dulu (Berkas → Buka data) "
                    + "atau muat contoh data, lalu pilih analisisnya lagi.",
                    "Belum ada data", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            JendelaAnalisis.Buka(_data, spec, this, JalankanAnalisis);
        }

        
        
        
        
        private void JalankanAnalisis(AnalysisSpec spec, RunContext konteks)
        {
            try
            {
                var blok = AnalysisRunner.Jalankan(spec, konteks);
                _ulangiSpec = spec;
                _ulangiKonteks = konteks;
                InfoAnalisis.Text = $"Terakhir: {spec.Name} — Ctrl+Enter untuk mengulang";
                TampilkanHasil(blok, spec.Name);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Analisis gagal", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        
        
        
        private void Ulangi_Click(object sender, RoutedEventArgs e)
        {
            if (_ulangiSpec == null || _ulangiKonteks == null)
            {
                MessageBox.Show(
                    "Belum ada analisis yang bisa diulang. Pilih alat dari menu Analisis "
                    + "atau tekan Ctrl+K lebih dulu.",
                    "Belum ada analisis", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            try
            {
                _ulangiKonteks.Data = _data;
                var blok = AnalysisRunner.Jalankan(_ulangiSpec, _ulangiKonteks);
                TampilkanHasil(blok, _ulangiSpec.Name);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Analisis gagal", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void BukaJendelaDeskriptif(AnalysisSpec spec)
        {
            if (_jendelaDeskriptif.TryGetValue(spec.Id, out var sudah) && sudah.IsLoaded)
            {
                sudah.Activate();
                return;
            }

            var jendela = new JendelaDeskriptif(_data, spec);
            jendela.Closed += (_, _) => _jendelaDeskriptif.Remove(spec.Id);
            _jendelaDeskriptif[spec.Id] = jendela;
            jendela.Show();
            jendela.Activate();
        }

        
        
        
        private void SalinHasil_Click(object sender, RoutedEventArgs e)
        {
            if (_keluaran.Count == 0)
            {
                MessageBox.Show(
                    "Belum ada keluaran yang bisa disalin.\n\n"
                    + "Jalankan analisis dulu (menu Analisis, atau Ctrl+K), "
                    + "baru tombol ini bisa dipakai.",
                    "Belum ada keluaran", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            try
            {
                Clipboard.SetText(TeksKeluaran());
                InfoAnalisis.Text = "Keluaran disalin ke clipboard";
            }
            catch (Exception ex)
            {
                TampilkanGalat(ex, "Gagal menyalin keluaran");
            }
        }

        
        
        
        private string TeksKeluaran()
        {
            var sb = new StringBuilder();
            sb.AppendLine("AlatStatistik — keluaran");
            sb.AppendLine(DateTime.Now.ToString("yyyy-MM-dd HH:mm"));
            sb.AppendLine(new string('=', 40));

            foreach (var entri in _keluaran)
            {
                sb.AppendLine();
                sb.AppendLine($"[{entri.Nomor}] {entri.Judul}  ({entri.Waktu})");
                sb.AppendLine(TeksHasil(entri.Blok, entri.Judul));
            }

            return sb.ToString();
        }

        
        
        
        private List<ResultBlock> SemuaBlok()
        {
            var semua = new List<ResultBlock>();
            foreach (var entri in _keluaran)
            {
                semua.Add(Blocks.Heading($"[{entri.Nomor}] {entri.Judul}  ·  {entri.Waktu}"));
                semua.AddRange(entri.Blok);
            }
            return semua;
        }

        
        
        
        private static string TeksHasil(List<ResultBlock> blok, string judul)
        {
            var sb = new StringBuilder();
            sb.AppendLine(judul);
            sb.AppendLine(new string('=', judul.Length));

            foreach (var b in blok)
            {
                switch (b.Kind)
                {
                    case BlockKind.Heading:
                        sb.AppendLine();
                        sb.AppendLine(b.Text);
                        break;

                    case BlockKind.Table:
                        if (!string.IsNullOrEmpty(b.Title)) sb.AppendLine(b.Title);
                        if (b.Columns.Count > 0) sb.AppendLine(string.Join("\t", b.Columns));
                        foreach (var baris in b.Rows) sb.AppendLine(string.Join("\t", baris));
                        if (!string.IsNullOrEmpty(b.Footnote)) sb.AppendLine(b.Footnote);
                        sb.AppendLine();
                        break;

                    case BlockKind.Rumus:
                        foreach (var r in b.RumusList)
                            sb.AppendLine($"{r.Nama}: {r.Bentuk}  ({r.LabelTahun})");
                        if (!string.IsNullOrEmpty(b.Text)) sb.AppendLine(b.Text);
                        break;

                    case BlockKind.Substitusi:
                        foreach (var l in b.Langkah)
                            sb.AppendLine($"{l.Uraian} {l.Hitungan}".Trim());
                        break;

                    case BlockKind.Note:
                        sb.AppendLine(b.Text);
                        break;

                    case BlockKind.Chart:
                        sb.AppendLine($"[grafik: {b.Chart?.Title ?? b.Title ?? b.Text}]");
                        break;
                }
            }

            return sb.ToString();
        }

        

        private void BukaData_Click(object sender, RoutedEventArgs e)
        {
            var dialog = new OpenFileDialog
            {
                Filter = DataImport.FilterBuka + "|Semua berkas (*.*)|*.*",
                Title = "Buka berkas data"
            };
            if (dialog.ShowDialog() == true)
            {
                
                
                
                
                try { Tampilkan(MuatDenganPilihLembar(dialog.FileName)); }
                catch (Exception ex) { MessageBox.Show(ex.Message, "Gagal memuat", MessageBoxButton.OK, MessageBoxImage.Error); }
            }
        }

        private static Dataset MuatDenganPilihLembar(string path)
        {
            if (!BukuExcel.TampaknyaXlsx(path)) return DataImport.Load(path);

            var lembar = BukuExcel.DaftarSheet(path);
            if (lembar.Count <= 1) return BukuExcel.Baca(path);

            int? pilih = JendelaInput.Pilih(
                "Pilih lembar kerja",
                $"Berkas ini berisi {lembar.Count} lembar. Mana yang berisi datanya?",
                lembar);
            if (pilih is null) throw new InvalidDataException("Pemilihan lembar dibatalkan.");

            return BukuExcel.Baca(path, lembar[pilih.Value]);
        }

        private void MuatContoh_Click(object sender, RoutedEventArgs e)
        {
            string? contoh = CariBerkas("samples", "data_uji.csv");
            if (contoh == null)
            {
                MessageBox.Show("Berkas contoh tidak ditemukan di folder samples.", "Contoh tidak ada",
                                MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }
            var contohDs = DataImport.LoadCsv(contoh);
            
            
            
            contohDs.SourcePath = null;
            contohDs.Name = "data_uji (contoh)";
            Tampilkan(contohDs);
        }

        

        private void DataBaru_Click(object sender, RoutedEventArgs e)
        {
            int? baris = JendelaInput.Angka("Data baru", "Berapa baris yang disiapkan?", 20, 1, 1_000_000);
            if (baris == null) return;

            int? kolom = JendelaInput.Angka("Data baru", "Berapa variabel (kolom)?", 3, 1, 500);
            if (kolom == null) return;

            App.TulisJejak($"data baru: {baris.Value} baris x {kolom.Value} variabel");
            var ds = Dataset.Baru(baris.Value, kolom.Value);
            ds.Riwayat.Add(DataChange.Struktur($"Data baru: {baris.Value} baris × {kolom.Value} variabel"));
            Tampilkan(ds);
            App.TulisJejak("data baru selesai ditampilkan");
        }

        private void SisipBaris_Click(object sender, RoutedEventArgs e)
        {
            if (_data.IsEmpty) { MessageBox.Show("Belum ada data. Buka berkas atau buat data baru lebih dulu."); return; }

            int? jumlah = JendelaInput.Angka("Sisipkan baris", "Berapa baris yang ditambahkan?", 1, 1, 100_000);
            if (jumlah == null) return;

            _data.TambahBaris(jumlah.Value);
            _data.Riwayat.Add(DataChange.Struktur($"Menambah {jumlah.Value} baris kosong"));
            SegarkanTampilanData();
            SegarkanRiwayat();
        }

        private void SisipKolom_Click(object sender, RoutedEventArgs e)
        {
            if (_data.IsEmpty) { MessageBox.Show("Belum ada data. Buka berkas atau buat data baru lebih dulu."); return; }

            string usul = _data.NamaVariabelUnik("V" + (_data.ColumnCount + 1));
            var jawab = JendelaInput.VariabelBaru("Sisipkan variabel", usul);
            if (jawab == null) return;

            string nama = string.IsNullOrWhiteSpace(jawab.Value.Nama) ? usul : jawab.Value.Nama;
            var v = _data.TambahVariabel(nama, jawab.Value.Ukur);
            _data.Riwayat.Add(DataChange.Struktur($"Menambah variabel '{v.Name}' ({v.Measure})"));
            SegarkanTampilanData();
            SegarkanRiwayat();
        }

        private void HapusKolom_Click(object sender, RoutedEventArgs e)
        {
            if (_data.IsEmpty) { MessageBox.Show("Belum ada data."); return; }

            string daftar = string.Join(", ", _data.Names);
            string? nama = JendelaInput.Teks("Hapus variabel",
                "Nama variabel yang dihapus.\nYang tersedia: " + daftar, "");
            if (string.IsNullOrWhiteSpace(nama)) return;

            int i = _data.IndexOf(nama);
            if (i < 0)
            {
                MessageBox.Show($"Tidak ada variabel bernama '{nama}'.", "Tidak ditemukan",
                                MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            string namaAsli = _data.Variables[i].Name;
            if (!_data.HapusVariabel(namaAsli))
            {
                MessageBox.Show("Variabel terakhir tidak boleh dihapus — tabel harus punya minimal satu kolom.",
                                "Tidak bisa dihapus", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            _data.Riwayat.Add(DataChange.Struktur($"Menghapus variabel '{namaAsli}'"));
            SegarkanTampilanData();
            SegarkanRiwayat();
        }

        private void Simpan_Click(object sender, RoutedEventArgs e)
        {
            if (_data.IsEmpty) { MessageBox.Show("Belum ada data untuk disimpan."); return; }

            if (string.IsNullOrEmpty(_data.SourcePath))
            {
                SimpanData_Click(sender, e);          
                return;
            }

            try
            {
                
                
                DataImport.PesanLabelTerakhir = null;
                DataImport.Simpan(_data, _data.SourcePath);
                _simpanTerakhir = _data.SourcePath;
                InfoData.Text = $"{Path.GetFileName(_data.SourcePath)} — "
                              + $"{_data.RowCount} baris × {_data.ColumnCount} variabel (tersimpan)";
                LaporkanLabelTersimpan();
            }
            catch (Exception ex)
            {
                TampilkanGalat(ex, "Gagal menyimpan");
            }
        }

        private void SimpanData_Click(object sender, RoutedEventArgs e)
        {
            if (_data.IsEmpty) { MessageBox.Show("Belum ada data untuk disimpan."); return; }

            var dialog = new SaveFileDialog
            {
                Filter = DataImport.FilterSimpan,
                FileName = _data.Name + ".xlsx",
                DefaultExt = ".xlsx"
            };
            if (dialog.ShowDialog() == true)
            {
                DataImport.PesanLabelTerakhir = null;
                DataImport.Simpan(_data, dialog.FileName);
                _data.SourcePath = dialog.FileName;   
                _simpanTerakhir = dialog.FileName;

                
                
                
                if (string.IsNullOrEmpty(DataImport.PesanLabelTerakhir))
                    MessageBox.Show("Data tersimpan.", "Selesai", MessageBoxButton.OK, MessageBoxImage.Information);
                else
                    LaporkanLabelTersimpan();
            }
        }

        
        
        
        
        
        private static void LaporkanLabelTersimpan()
        {
            if (string.IsNullOrEmpty(DataImport.PesanLabelTerakhir)) return;

            MessageBox.Show(DataImport.PesanLabelTerakhir, "Label variabel",
                            MessageBoxButton.OK, MessageBoxImage.Information);
            DataImport.PesanLabelTerakhir = null;
        }

        private void Keluar_Click(object sender, RoutedEventArgs e) => Close();

        
        
        
        private void EksporDocx_Click(object sender, RoutedEventArgs e)
        {
            if (_keluaran.Count == 0)
            {
                MessageBox.Show(
                    "Belum ada keluaran yang bisa diekspor.\n\n"
                    + "Jalankan analisis dulu (menu Analisis, atau Ctrl+K). "
                    + "Hasilnya dikumpulkan di tab Keluaran, lalu tombol ini menyimpannya "
                    + "menjadi satu berkas Word (.docx) — semua tabel jadi tabel asli "
                    + "yang bisa diedit dan diformat di Word.",
                    "Belum ada keluaran", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            string namaBerkas = _keluaran.Count == 1
                ? _keluaran[0].Judul
                : $"keluaran-{_keluaran.Count}-analisis";
            foreach (char c in Path.GetInvalidFileNameChars()) namaBerkas = namaBerkas.Replace(c, '-');

            var dialog = new SaveFileDialog
            {
                Filter = EksporDocx.FilterDialog,
                FileName = namaBerkas + EksporDocx.PerluasanBerkas,
                DefaultExt = EksporDocx.PerluasanBerkas
            };
            if (dialog.ShowDialog() != true) return;

            try
            {
                string namaData = string.IsNullOrWhiteSpace(_data.SourcePath) ? _data.Name
                                : Path.GetFileName(_data.SourcePath);

                string judul = _keluaran.Count == 1
                    ? _keluaran[0].Judul
                    : $"Keluaran {_keluaran.Count} analisis — {namaData}";

                EksporDocx.Simpan(dialog.FileName, SemuaBlok(), judul, namaData);

                var jawab = MessageBox.Show(
                    $"Laporan Word tersimpan ke\n{dialog.FileName}\n\n"
                    + "Tabel di dalamnya adalah tabel asli Word — bisa diketik ulang, "
                    + "diubah formatnya, dan disisipkan grafik dari datanya.\n\n"
                    + "Buka sekarang?",
                    "Selesai", MessageBoxButton.YesNo, MessageBoxImage.Information);
                if (jawab == MessageBoxResult.Yes)
                    Process.Start(new ProcessStartInfo(dialog.FileName) { UseShellExecute = true });

                InfoAnalisis.Text = "Keluaran diekspor ke Word (tabel asli)";
            }
            catch (Exception ex)
            {
                TampilkanGalat(ex, "Gagal mengekspor laporan Word");
            }
        }

        private void EksporHtml_Click(object sender, RoutedEventArgs e)
        {
            if (_keluaran.Count == 0)
            {
                MessageBox.Show(
                    "Belum ada keluaran yang bisa diekspor.\n\n"
                    + "Jalankan analisis dulu (menu Analisis, atau Ctrl+K). "
                    + "Hasilnya dikumpulkan di tab Keluaran, lalu tombol ini menyimpannya "
                    + "menjadi satu berkas laporan HTML.",
                    "Belum ada keluaran", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            string namaBerkas = _keluaran.Count == 1
                ? _keluaran[0].Judul
                : $"keluaran-{_keluaran.Count}-analisis";
            foreach (char c in Path.GetInvalidFileNameChars()) namaBerkas = namaBerkas.Replace(c, '-');

            var dialog = new SaveFileDialog
            {
                Filter = "Laporan HTML (*.html)|*.html",
                FileName = namaBerkas + ".html",
                DefaultExt = ".html"
            };
            if (dialog.ShowDialog() != true) return;

            try
            {
                string namaData = string.IsNullOrWhiteSpace(_data.SourcePath) ? _data.Name
                                : Path.GetFileName(_data.SourcePath);

                string judul = _keluaran.Count == 1
                    ? _keluaran[0].Judul
                    : $"Keluaran {_keluaran.Count} analisis — {namaData}";

                EksporHtml.Simpan(dialog.FileName, SemuaBlok(), judul, namaData);

                var jawab = MessageBox.Show(
                    $"Laporan tersimpan ke\n{dialog.FileName}\n\nBuka sekarang?",
                    "Selesai", MessageBoxButton.YesNo, MessageBoxImage.Information);
                if (jawab == MessageBoxResult.Yes)
                    Process.Start(new ProcessStartInfo(dialog.FileName) { UseShellExecute = true });

                InfoAnalisis.Text = "Keluaran diekspor ke HTML";
            }
            catch (Exception ex)
            {
                TampilkanGalat(ex, "Gagal mengekspor laporan");
            }
        }

        private void UrutkanVariabel_Click(object sender, RoutedEventArgs e)
        {
            if (_data.IsEmpty) { BelumAdaData(); return; }

            var opsi = new[]
            {
                "Nama variabel, A → Z",
                "Nama variabel, Z → A",
                "Tingkat ukur (Skala → Ordinal → Nominal)",
                "Balik urutan sekarang"
            };

            int? pilih = JendelaInput.Pilih("Urutkan variabel",
                                            "Pilih cara mengurutkan kolom:", opsi);
            if (pilih == null) return;

            var mode = (ModeUrutVariabel)pilih.Value;
            try
            {
                TampilkanHasil(UrutVariabel.Terapkan(_data, mode), "Urutkan variabel");
                SegarkanTampilanData();
            }
            catch (Exception ex)
            {
                TampilkanGalat(ex, "Pengurutan gagal");
            }
        }

        private void UjiValidasi_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                string? acuan = CariBerkas("docs", "acuan_scipy.json");
                if (acuan == null)
                {
                    MessageBox.Show(
                        "Berkas docs/acuan_scipy.json tidak ditemukan.\n"
                        + "Buat dulu dengan menjalankan: python tools/uji_algoritma.py",
                        "Acuan belum ada", MessageBoxButton.OK, MessageBoxImage.Information);
                    return;
                }

                string? data = CariBerkas("samples", "data_uji.csv");
                Dataset? ds = data != null ? DataImport.LoadCsv(data) : null;

                var hasil = Validator.Jalankan(acuan, ds);
                new ValidationWindow(hasil).ShowDialog();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Uji validasi gagal", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void KonversiBerkas_Click(object sender, RoutedEventArgs e)
        {
            var buka = new OpenFileDialog
            {
                Filter = DataImport.FilterBuka,
                Title = "Pilih berkas data yang akan dikonversi"
            };
            if (buka.ShowDialog() != true) return;

            var simpan = new SaveFileDialog
            {
                Filter = DataImport.FilterSimpan,
                FileName = Path.ChangeExtension(Path.GetFileName(buka.FileName), ".xlsx"),
                DefaultExt = ".xlsx"
            };
            if (simpan.ShowDialog() != true) return;

            try
            {
                Dataset ds = DataImport.Load(buka.FileName);
                DataImport.Simpan(ds, simpan.FileName);
                MessageBox.Show(
                    $"Konversi selesai.\n{Path.GetFileName(simpan.FileName)}\n\n"
                    + $"{ds.RowCount} baris, {ds.ColumnCount} kolom.",
                    "Konversi berkas data", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Konversi gagal", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        

        private void LaporanKualitas_Click(object sender, RoutedEventArgs e)
        {
            if (_data.IsEmpty) { BelumAdaData(); return; }

            try { TampilkanHasil(KualitasData.Laporan(_data), "Laporan kualitas data"); }
            catch (Exception ex) { TampilkanGalat(ex, "Laporan kualitas gagal"); }
        }

        private void BukaPembersihan(int operasi)
        {
            if (_data.IsEmpty) { BelumAdaData(); return; }

            var jendela = new JendelaPembersih(_data, operasi) { Owner = this };
            if (jendela.ShowDialog() != true) return;

            
            _cadanganData = _data.Clone();

            try
            {
                var hasil = jendela.Jalankan(_data);

                if (!hasil.AdaPerubahan)
                {
                    _cadanganData = null;
                    MessageBox.Show("Tidak ada yang berubah.\n\n" + string.Join("\n", hasil.Rincian),
                                    "Pembersihan data", MessageBoxButton.OK, MessageBoxImage.Information);
                    return;
                }

                SegarkanTampilanData();
                TampilkanHasil(hasil.KeBlok(), "Pembersihan data");
            }
            catch (Exception ex)
            {
                _cadanganData = null;
                TampilkanGalat(ex, "Pembersihan gagal");
            }
        }

        private void TanganiKosong_Click(object sender, RoutedEventArgs e) => BukaPembersihan(0);

        private void TanganiPencilan_Click(object sender, RoutedEventArgs e) => BukaPembersihan(3);

        private void BuangDuplikat_Click(object sender, RoutedEventArgs e)
        {
            if (_data.IsEmpty) { BelumAdaData(); return; }

            int jumlah = PembersihData.HitungDuplikat(_data);
            if (jumlah == 0)
            {
                MessageBox.Show("Tidak ada baris duplikat.", "Buang baris duplikat",
                                MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            var tanya = MessageBox.Show(
                $"Ada {jumlah} baris yang isinya sama persis dengan baris lain.\n"
                + $"Buang baris itu? Data tinggal {_data.RowCount - jumlah} dari {_data.RowCount} baris.\n\n"
                + "Bisa diurungkan lewat Data → Urungkan perubahan terakhir.",
                "Buang baris duplikat", MessageBoxButton.YesNo, MessageBoxImage.Question);

            if (tanya != MessageBoxResult.Yes) return;

            _cadanganData = _data.Clone();

            try
            {
                var hasil = PembersihData.BuangDuplikat(_data);
                SegarkanTampilanData();
                TampilkanHasil(hasil.KeBlok(), "Buang baris duplikat");
            }
            catch (Exception ex)
            {
                _cadanganData = null;
                TampilkanGalat(ex, "Pembersihan gagal");
            }
        }

        private void Normalisasi_Click(object sender, RoutedEventArgs e) => OlahData(0);

        private void Pengkodean_Click(object sender, RoutedEventArgs e) => OlahData(1);

        private void BagiData_Click(object sender, RoutedEventArgs e) => OlahData(2);

        private void OlahData(int operasi)
        {
            if (_data.IsEmpty) { BelumAdaData(); return; }

            string judulKeluaran = operasi switch { 0 => "Normalisasi", 1 => "Ubah kategori jadi angka", _ => "Bagi data latih & uji" };

            var jendela = new JendelaOlah(_data, operasi) { Owner = this };
            if (jendela.ShowDialog() != true) return;

            _cadanganData = _data.Clone();

            try
            {
                var blok = jendela.Jalankan(_data);
                SegarkanTampilanData();
                TampilkanHasil(blok, judulKeluaran);
            }
            catch (Exception ex)
            {
                _cadanganData = null;
                TampilkanGalat(ex, "Operasi gagal");
            }
        }

        private void UrutkanBaris_Click(object sender, RoutedEventArgs e) => PekerjaanBaris(0);

        private void PilihKasus_Click(object sender, RoutedEventArgs e) => PekerjaanBaris(1);

        private void PekerjaanBaris(int operasi)
        {
            if (_data.IsEmpty) { BelumAdaData(); return; }

            string judulKeluaran = operasi == 0 ? "Urutkan baris" : "Pilih kasus";

            var jendela = new JendelaBaris(_data, operasi) { Owner = this };
            if (jendela.ShowDialog() != true) return;

            _cadanganData = _data.Clone();

            try
            {
                var blok = jendela.Jalankan(_data);
                SegarkanTampilanData();
                TampilkanHasil(blok, judulKeluaran);
            }
            catch (Exception ex)
            {
                _cadanganData = null;
                TampilkanGalat(ex, "Operasi gagal");
            }
        }

        private void HitungVariabel_Click(object sender, RoutedEventArgs e)
        {
            if (_data.IsEmpty) { BelumAdaData(); return; }

            var jendela = new JendelaHitung(_data) { Owner = this };
            if (jendela.ShowDialog() != true) return;

            _cadanganData = _data.Clone();

            try
            {
                var h = Ekspresi.Hitung(jendela.TeksEkspresi, _data);
                if (!h.Sukses)
                {
                    _cadanganData = null;
                    MessageBox.Show(h.Galat, "Ekspresi tidak bisa dipakai",
                                    MessageBoxButton.OK, MessageBoxImage.Warning);
                    return;
                }

                var nilai = h.Nilai
                    .Select(v => v.HasValue
                        ? v.Value.ToString("G12", System.Globalization.CultureInfo.InvariantCulture)
                        : null)
                    .ToList();

                int i = Bantu.TambahKolom(_data, jendela.NamaTujuan, nilai);
                string namaTerpasang = _data.Names[i];

                SegarkanTampilanData();
                TampilkanHasil(RingkasanHitung(jendela.TeksEkspresi, namaTerpasang, h), "Hitung variabel");
            }
            catch (Exception ex)
            {
                _cadanganData = null;
                TampilkanGalat(ex, "Hitung variabel gagal");
            }
        }

        private static List<ResultBlock> RingkasanHitung(string teks, string kolom, HasilHitung h)
        {
            var ci = System.Globalization.CultureInfo.InvariantCulture;
            var blok = new List<ResultBlock> { Blocks.Heading("Hitung variabel") };

            blok.Add(Blocks.Note($"Kolom **{kolom}** dibuat dari ekspresi `{teks}`."));

            int hilang = h.Nilai.Count(v => v is null);
            blok.Add(Blocks.Note($"{h.Nilai.Count} baris dihitung; {hilang} di antaranya kosong "
                                 + $"karena ada nilai hilang di variabel yang dipakai."));

            var baris = new List<List<string>>();
            int batas = Math.Min(10, h.Nilai.Count);
            for (int r = 0; r < batas; r++)
                baris.Add(new List<string> { (r + 1).ToString(ci), h.Nilai[r] is { } v ? v.ToString("G10", ci) : "(hilang)" });

            blok.Add(Blocks.Table("Sepuluh baris pertama",
                                  new[] { "Baris", kolom }, baris,
                                  h.Nilai.Count > batas ? $"Dan {h.Nilai.Count - batas} baris lagi." : null));

            var ada = h.Nilai.Where(v => v.HasValue).Select(v => v!.Value).ToList();
            if (ada.Count > 0)
                blok.Add(Blocks.Note($"Rerata {ada.Average():G8}, terkecil {ada.Min():G8}, terbesar {ada.Max():G8}."));

            return blok;
        }

        private void BeriPeringkat_Click(object sender, RoutedEventArgs e) => Transformasi(0);

        private void UbahNilai_Click(object sender, RoutedEventArgs e) => Transformasi(1);

        private void IsiNilaiHilang_Click(object sender, RoutedEventArgs e) => Transformasi(2);

        private void Transformasi(int operasi)
        {
            if (_data.IsEmpty) { BelumAdaData(); return; }

            string judulKeluaran = operasi switch { 0 => "Beri peringkat", 1 => "Ubah nilai (recode)", _ => "Isi nilai hilang" };

            var jendela = new JendelaTransformasi(_data, operasi) { Owner = this };
            if (jendela.ShowDialog() != true) return;

            _cadanganData = _data.Clone();

            try
            {
                var blok = jendela.Jalankan(_data);
                SegarkanTampilanData();
                TampilkanHasil(blok, judulKeluaran);
            }
            catch (Exception ex)
            {
                _cadanganData = null;
                TampilkanGalat(ex, "Transformasi gagal");
            }
        }

        private void GrafikHistogram_Click(object sender, RoutedEventArgs e) => BuatGrafik(0);

        private void GrafikBox_Click(object sender, RoutedEventArgs e) => BuatGrafik(1);

        private void GrafikPencar_Click(object sender, RoutedEventArgs e) => BuatGrafik(2);

        private void GrafikBatang_Click(object sender, RoutedEventArgs e) => BuatGrafik(3);

        private void GrafikGaris_Click(object sender, RoutedEventArgs e) => BuatGrafik(4);

        private void GrafikLingkaran_Click(object sender, RoutedEventArgs e) => BuatGrafik(5);

        private void GrafikPetaPanas_Click(object sender, RoutedEventArgs e) => BuatGrafik(6);

        private void BuatGrafik(int jenis)
        {
            if (_data.IsEmpty) { BelumAdaData(); return; }

            var jendela = new JendelaGrafik(_data, jenis) { Owner = this };
            if (jendela.ShowDialog() != true) return;

            try { TampilkanHasil(jendela.Buat(_data), "Grafik"); }
            catch (Exception ex) { TampilkanGalat(ex, "Grafik gagal"); }
        }

        private void UrungkanPerubahan_Click(object sender, RoutedEventArgs e)
        {
            if (_cadanganData == null)
            {
                MessageBox.Show("Tidak ada perubahan data yang bisa diurungkan.\n"
                                + "Cadangan hanya dibuat setelah pembersihan, normalisasi, "
                                + "pengkodean, atau pembagian data diterapkan.",
                                "Urungkan perubahan", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            Tampilkan(_cadanganData);
            _cadanganData = null;

            MessageBox.Show($"Data dikembalikan: {_data.RowCount} baris × {_data.ColumnCount} variabel.",
                            "Urungkan perubahan", MessageBoxButton.OK, MessageBoxImage.Information);
        }

        

        private void Urubahan_Click(object sender, RoutedEventArgs e) => UrubahanTerakhir();

        private void UrubahanTerakhir()
        {
            if (_data.Riwayat.Count == 0)
            {
                SystemSounds.Beep.Play();
                return;
            }

            
            
            var diurungkan = _data.UndoLast();

            if (diurungkan == null)
            {
                
                
                MessageBox.Show(
                    "Perubahan terakhir menyangkut bentuk tabel (menambah baris, "
                    + "menambah atau menghapus variabel).\n\n"
                    + "Perubahan semacam itu tidak dibalik oleh Ctrl+Z — catatannya "
                    + "tetap disimpan di sini supaya jejaknya tidak hilang. Untuk "
                    + "membuang baris atau kolom, sunting langsung di tabel.",
                    "Tidak bisa diurungkan", MessageBoxButton.OK, MessageBoxImage.Information);
                SegarkanRiwayat();
                return;
            }

            SegarkanTampilanData();
            SegarkanRiwayat();
        }

        private void BersihkanRiwayat_Click(object sender, RoutedEventArgs e)
        {
            if (_data.Riwayat.Count == 0) return;
            var jawab = MessageBox.Show(
                $"Ada {_data.Riwayat.Count} perubahan tercatat di riwayat.\n"
                + "Catatan ini tidak akan menghapus data — suntingan yang sudah "
                + "dilakukan tetap ada. Yang dihapus hanya catatan perubahannya.\n\n"
                + "Yakin bersihkan?",
                "Bersihkan riwayat", MessageBoxButton.YesNo, MessageBoxImage.Question);
            if (jawab != MessageBoxResult.Yes) return;

            _data.Riwayat.Clear();
            SegarkanRiwayat();
        }

        public void SegarkanRiwayat()
        {
            GridRiwayat.ItemsSource = _data.Riwayat.OrderBy(c => c.Waktu).ToList();
            TombolUndo.IsEnabled = _data.Riwayat.Count > 0;
            TombolBersihkanRiwayat.IsEnabled = _data.Riwayat.Count > 0;

            InfoRiwayat.Text = _data.Riwayat.Count switch
            {
                0 => "Tidak ada perubahan tercatat.",
                1 => "1 perubahan tercatat · Ctrl+Z untuk urungkan.",
                _ => $"{_data.Riwayat.Count} perubahan tercatat · Ctrl+Z untuk urungkan yang paling akhir."
            };
        }

        private void Tentang_Click(object sender, RoutedEventArgs e)
        {
            MessageBox.Show(
                "AlatStatistik versi 0.1\n\n"
                + "Aplikasi analisis statistik open source (lisensi MIT).\n"
                + "Semua perhitungan ditulis sendiri dan diperiksa terhadap SciPy.\n\n"
                + "Menu Alat → Uji validasi menampilkan perbandingan angkanya.",
                "Tentang AlatStatistik", MessageBoxButton.OK, MessageBoxImage.Information);
        }

        

        
        
        
        
        
        
        private void TampilkanHasil(List<ResultBlock> blok, string judul)
        {
            var entri = new EntriKeluaran
            {
                Nomor = _keluaran.Count + 1,
                Judul = judul,
                Waktu = DateTime.Now.ToString("HH:mm:ss"),
                Blok = blok
            };

            entri.Kartu = BuatKartuKeluaran(entri);

            _keluaran.Add(entri);
            PanelHasil.Children.Add(entri.Kartu);

            SegarkanKeluaran();

            
            
            TabUtama.SelectedIndex = 2;
            Dispatcher.BeginInvoke(new Action(() =>
            {
                DaftarKeluaran.SelectedIndex = _keluaran.Count - 1;
                entri.Kartu.BringIntoView();
            }), System.Windows.Threading.DispatcherPriority.Loaded);
        }

        
        
        
        private Border BuatKartuKeluaran(EntriKeluaran entri)
        {
            var kartu = new Border
            {
                Style = (Style)FindResource("Kartu"),
                Margin = new Thickness(0, 0, 0, 12)
            };
            AutomationProperties.SetName(kartu, $"Keluaran {entri.Nomor}: {entri.Judul}");

            var isi = new DockPanel { LastChildFill = true };

            var kepala = new Border
            {
                Background = (Brush)FindResource("Panel2"),
                BorderBrush = (Brush)FindResource("Garis"),
                BorderThickness = new Thickness(0, 0, 0, 1),
                Padding = new Thickness(12, 8, 12, 8),
                Margin = new Thickness(-12, -12, -12, 10)
            };
            DockPanel.SetDock(kepala, Dock.Top);

            var barisKepala = new DockPanel { LastChildFill = true };

            var waktu = new TextBlock
            {
                Text = entri.Waktu,
                FontSize = 11,
                Foreground = (Brush)FindResource("TeksRedup"),
                VerticalAlignment = VerticalAlignment.Center,
                Margin = new Thickness(10, 0, 0, 0)
            };
            DockPanel.SetDock(waktu, Dock.Right);
            barisKepala.Children.Add(waktu);

            barisKepala.Children.Add(new TextBlock
            {
                Text = $"{entri.Nomor}. {entri.Judul}",
                FontWeight = FontWeights.SemiBold,
                Foreground = (Brush)FindResource("Aksen")
            });

            kepala.Child = barisKepala;
            isi.Children.Add(kepala);

            isi.Children.Add(ResultsRenderer.Render(entri.Blok));

            kartu.Child = isi;
            return kartu;
        }

        
        
        
        private void SegarkanKeluaran()
        {
            bool kosong = _keluaran.Count == 0;

            KeadaanKosong.Visibility = kosong ? Visibility.Visible : Visibility.Collapsed;
            GulirKeluaran.Visibility = kosong ? Visibility.Collapsed : Visibility.Visible;

            DaftarKeluaran.ItemsSource = null;
            DaftarKeluaran.ItemsSource = _keluaran;

            InfoKeluaran.Text = kosong
                ? "Belum ada keluaran."
                : _keluaran.Count == 1
                    ? "1 analisis. Klik untuk meloncat ke hasilnya."
                    : $"{_keluaran.Count} analisis, yang terbaru di bawah. Klik untuk meloncat.";

            TabKeluaran.Header = kosong ? "_Keluaran" : $"_Keluaran ({_keluaran.Count})";

                TombolEksporKeluaran.IsEnabled = !kosong;
                TombolEksporHtmlKeluaran.IsEnabled = !kosong;
                TombolSalinKeluaran.IsEnabled = !kosong;
            TombolBersihkanKeluaran.IsEnabled = !kosong;
        }

        
        
        
        private void DaftarKeluaran_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (DaftarKeluaran.SelectedItem is EntriKeluaran entri && entri.Kartu != null)
                entri.Kartu.BringIntoView();
        }

        
        
        private void BersihkanKeluaran_Click(object sender, RoutedEventArgs e)
        {
            if (_keluaran.Count == 0) return;

            var jawab = MessageBox.Show(
                $"Buang {_keluaran.Count} keluaran dari jendela ini?\n\n"
                + "Data dan berkas laporan yang sudah tersimpan tidak terpengaruh.",
                "Bersihkan keluaran", MessageBoxButton.YesNo, MessageBoxImage.Question);
            if (jawab != MessageBoxResult.Yes) return;

            _keluaran.Clear();
            PanelHasil.Children.Clear();
            SegarkanKeluaran();
        }

        private static void BelumAdaData()
            => MessageBox.Show("Belum ada data. Buka berkas CSV atau muat contoh data dulu.",
                               "Belum ada data", MessageBoxButton.OK, MessageBoxImage.Information);

        private static void TampilkanGalat(Exception ex, string judul)
            => MessageBox.Show(ex.Message, judul, MessageBoxButton.OK, MessageBoxImage.Error);

        private void GridData_BeginningEdit(object sender, DataGridBeginningEditEventArgs e)
        {
            if (e.Row.Item is not DataRowView baris) { _nilaiSebelumEdit = null; return; }
            _nilaiSebelumEdit = baris[e.Column.DisplayIndex] as string;
        }

        private void GridData_CellEditEnding(object sender, DataGridCellEditEndingEventArgs e)
        {
            
            if (e.Row.Item is not DataRowView baris) return;
            if (GridData.ItemsSource is not DataView view) return;
            if (e.EditAction != DataGridEditAction.Commit) return;

            int rowIndex = -1;
            for (int i = 0; i < view.Count; i++)
            {
                if (ReferenceEquals(view[i], baris)) { rowIndex = i; break; }
            }
            if (rowIndex < 0) return;

            string? nilaiBaru = baris[e.Column.DisplayIndex] as string;
            string namaKolom = e.Column.Header?.ToString() ?? "";
            if (string.IsNullOrEmpty(namaKolom)) return;

            
            
            string? nilaiLama = _nilaiSebelumEdit;
            _nilaiSebelumEdit = null;

            Dispatcher.BeginInvoke(new Action(() =>
            {
                try
                {
                    _data.FromDataTable(view!.Table!);
                    InfoData.Text = $"{Path.GetFileName(_data.SourcePath ?? _data.Name)} — {_data.RowCount} baris × {_data.ColumnCount} variabel";

                    if (!string.Equals(nilaiLama ?? "", nilaiBaru ?? "", StringComparison.Ordinal))
                    {
                        _data.Riwayat.Add(new DataChange
                        {
                            Baris = rowIndex,
                            Kolom = namaKolom,
                            NilaiLama = nilaiLama,
                            NilaiBaru = nilaiBaru
                        });
                    }
                    SegarkanRiwayat();
                }
                catch (Exception ex)
                {
                    
                    
                    App.TulisLog(ex);
                }
            }));
        }

        
        private string? _namaVariabelSebelum;

        private void GridVariabel_BeginningEdit(object sender, DataGridBeginningEditEventArgs e)
        {
            _namaVariabelSebelum = e.Row.Item is Variable v ? v.Name : null;
        }

        private void GridVariabel_CellEditEnding(object sender, DataGridCellEditEndingEventArgs e)
        {
            if (e.EditAction != DataGridEditAction.Commit) return;
            if (e.Row.Item is not Variable v) return;

            
            
            
            
            
            string kolom = e.Column.Header?.ToString() ?? "";
            string? nilaiBaru = e.EditingElement switch
            {
                TextBox tb => tb.Text,
                ComboBox cb => cb.SelectedItem?.ToString(),
                _ => null
            };

            
            
            
            
            
            if (nilaiBaru == null)
            {
                TerapkanVariabel(v);
                return;
            }

            string? namaLama = _namaVariabelSebelum;
            _namaVariabelSebelum = null;

            switch (kolom)
            {
                case KeteranganKolomVariabel.Nama:
                    {
                        
                        if (string.IsNullOrWhiteSpace(nilaiBaru)) { TerapkanVariabel(v); return; }

                        
                        
                        
                        
                        
                        if (namaLama != null
                            && !string.Equals(namaLama, v.Name, StringComparison.Ordinal)
                            && string.Equals(v.Name, nilaiBaru, StringComparison.Ordinal))
                        {
                            v.Name = namaLama;
                        }

                        
                        if (!GantiNama(v, nilaiBaru)) TerapkanVariabel(v);
                        return;
                    }

                case KeteranganKolomVariabel.Label:
                    v.Label = nilaiBaru.Trim();
                    break;

                case KeteranganKolomVariabel.Desimal:
                    if (int.TryParse(nilaiBaru, out int dec)) v.Decimals = Math.Clamp(dec, 0, 10);
                    break;

                case KeteranganKolomVariabel.TingkatUkur:
                    if (Enum.TryParse<Measure>(nilaiBaru, out var m)) v.Measure = m;
                    break;
            }

            TerapkanVariabel(v);
        }

        private void TerapkanVariabel(Variable? fokus = null)
        {
            Dispatcher.BeginInvoke(new Action(() =>
            {
                
                
                
                
                try
                {
                    App.TulisJejak("TerapkanVariabel mulai");
                    DataImport.InferMeasures(_data);
                    GridData.ItemsSource = _data.ToDataTable().DefaultView;
                    InfoData.Text = $"{Path.GetFileName(_data.SourcePath ?? _data.Name)} — "
                                  + $"{_data.RowCount} baris × {_data.ColumnCount} variabel";
                    SegarkanRiwayat();

                    
                    
                    
                    
                    
                    
                    
                    
                    App.TulisJejak("TerapkanVariabel selesai");
                }
                catch (Exception ex)
                {
                    TampilkanGalat(ex, "Gagal menyegarkan tabel setelah perubahan variabel");
                }
            }));
        }

        
        

        private bool GantiNama(Variable v, string namaBaru)
        {
            string bersih = (namaBaru ?? "").Trim();
            if (bersih.Length == 0) return false;
            if (string.Equals(v.Name, bersih, StringComparison.Ordinal)) return false;

            int bentrok = _data.IndexOf(bersih);
            if (bentrok >= 0 && !ReferenceEquals(_data.Variables[bentrok], v))
            {
                MessageBox.Show($"Sudah ada variabel bernama '{bersih}'.\n"
                                + "Nama variabel harus berbeda satu sama lain; huruf besar/kecil "
                                + "tidak dibedakan (sama seperti lazimnya).",
                                "Nama kembar", MessageBoxButton.OK, MessageBoxImage.Information);
                return false;
            }

            
            
            var entri = _data.GantiNama(v.Name, bersih);
            if (entri == null) return false;

            TerapkanVariabel(v);
            return true;
        }

        private void GantiNamaKolom_Click(object sender, RoutedEventArgs e)
        {
            if (_data.IsEmpty) { MessageBox.Show("Belum ada data."); return; }

            var target = GridVariabel.SelectedItem as Variable;
            if (target == null)
            {
                string? dicari = JendelaInput.Teks("Ganti nama variabel",
                    "Nama variabel yang diganti.\nYang tersedia: " + string.Join(", ", _data.Names), "");
                if (string.IsNullOrWhiteSpace(dicari)) return;

                int i = _data.IndexOf(dicari);
                if (i < 0)
                {
                    MessageBox.Show($"Tidak ada variabel bernama '{dicari}'.",
                                    "Tidak ditemukan", MessageBoxButton.OK, MessageBoxImage.Warning);
                    return;
                }
                target = _data.Variables[i];
            }

            string? baru = JendelaInput.Teks("Ganti nama variabel",
                $"Nama baru untuk '{target.Name}':", target.Name);
            if (string.IsNullOrWhiteSpace(baru)) return;

            if (!GantiNama(target, baru)) return;

            
            GridVariabel.SelectedItem = target;
            GridVariabel.ScrollIntoView(target);
        }

        internal static string? CariBerkas(string folder, string nama)
        {
            var dir = new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory);
            while (dir != null)
            {
                string kandidat = Path.Combine(dir.FullName, folder, nama);
                if (File.Exists(kandidat)) return kandidat;

                
                kandidat = Path.Combine(dir.FullName, nama);
                if (File.Exists(kandidat) && string.Equals(dir.Name, folder, StringComparison.OrdinalIgnoreCase))
                    return kandidat;

                dir = dir.Parent;
            }
            return null;
        }

        
        
        
        
        
        private void Jendela_UkuranBerubah(object sender, SizeChangedEventArgs e)
        {
            double w = ActualWidth;
            KolomKerangka.Width = new GridLength(w >= 1400 ? 260 : w >= 1100 ? 230 : 190);
        }
    }

    
    
    
    public sealed class EntriKeluaran
    {
        public int Nomor { get; set; }
        public string Judul { get; set; } = "";
        public string Waktu { get; set; } = "";
        public List<ResultBlock> Blok { get; set; } = new();

        
        
        
        public FrameworkElement? Kartu { get; set; }
    }
}
